### ISSUE TITLE
Create monaca_config.json if it does not exist.

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-lib#1]
When clean installing monaca-cli and configure a proxy server, it will return an error like the one below.

```
# monaca proxy set http://localhost:1080      
Unable to set proxy server: Error: ENOENT, open '/root/.cordova/monaca_config.json'
```

Can you please create the configuration file if it is not found?

**Comment by argelius** [comment]
Thanks. I will create the file.

**Comment by argelius** [comment]
This is fixed now.
