### ISSUE TITLE
Dependant on npm

### ISSUE THREAD

**Issue by argelius** [monaca/monaca-lib#10]
Hi @JW-Vinayak 

I saw it spawns npm in the `replaceTemplate` method. This will fail if npm is not installed since it's not trying to execute a local npm version.

**Comment by JW-Vinayak** [comment]
So what would be the ideal solution @argelius?  Shall we display a dialog to users asking them to install npm.

**Comment by argelius** [comment]
@JW-Vinayak I will leave it as it is for now.

I will probably write a new function that pulls the templates from the Cloud instead so maybe we don't need to worry about this.
