### ISSUE TITLE
No longer able to login

### ISSUE THREAD

**Issue by hereiam133** [monaca/monaca-lib#121]
With this latest release of the cli (2.5.0), the lib no longer allows logging in.  

We have the following gulp task setup (and have tried adding a logout function 1st to clear whatever is in the mem)

```
gulp.task('monaca-login', (done) => {
     monaca.login(monacaEmail, monacaPassword).then(
        () => {
            done();
        },
        (error) => {
            console.log('monaca-login', error);
            if (error) throw error;
        }
    );
});
```

this results in the following issue

monaca-login { status: 'fail',
  code: 400,
  message: 'Your client is old version. Please upgrade to the latest version.' }

**Comment by andipavllo** [comment]
`monaca-lib` requires the `clientType` to be specified during its initialization. For example:

```
var Monaca = require('monaca-lib').Monaca,
   monaca = new Monaca({clientType: 'api'});
```

We haven't included it in the getting started guide because we didn't think many developers would have been interested in using it standalone but I guess it's time now.

**Comment by hereiam133** [comment]
@andipavllo Thank you, that has solved the issue, it would be great to have that added to the readme!

**Comment by andipavllo** [comment]
@hereiam133 just did it. I suggest you to use `clientType: 'lib'` instead of `api`, we have enabled it just for this purpose. Sorry for the trouble!
