### ISSUE TITLE
comuter name numbering

### ISSUE THREAD

**Issue by YoshinoriWakabayashi** [monaca/monaca-lib#2]
When I restart 'moncaca livesync' command
then computer name numbering ( user name's PC #Number )  increase
Is it correct behavior? 

コンピュータ名 #番号 が monaca livesync を再起動するたびにあがっていきますが、
これは意図した動作でしょうか？

例:
1,
ユーザー名's PC #1 が表示
2,
monaca livesync 再起動
3,
ユーザー名's PC #2 が表示

**Comment by argelius** [comment]
若林さん、ありがとうございます。

コンピュータ名はログインするときにサーバーサイドが返すので、なんでその番号が上がるか分かりません。浦本さんに聞いてみます。

**Comment by argelius** [comment]
Fixed. Will now send 'clientId' parameter so the Computer name doesn't change.
