### ISSUE TITLE
Ability to filter what files to ignore when doing upload and download

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-lib#22]
Please add a feature like `.gitignore` for monaca cli and localkit.
When there is a file called `.monacaignore` in the project dir, the specified files and directories will not uploaded and downloaded.

Please implement in a different branch called `monacaignore`.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

We have two points to consider
- `monaca upload` allows only files in /www, /merges and /plugins folders and selected few files in /platforms directory
- `qLimit` is implemented so that irrespective of number of files, the upload process will work fine.

Do we really need to add functionality to handle `.monacaignore` files?

**Comment by masahirotanaka** [comment]
Yes. It is still important to allow users to ignore.

**Comment by JW-Vinayak** [comment]
Ok then,  I will start working on this.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

I am done with implementing .monacaignore functionality. Following is the format that is supported.

`www/cantAllow`
`www/example3/index1.html`
`www/example2/exp`
`exp.txt`

**Comment by masahirotanaka** [comment]
Saw it. Can you please use `glob` npm module instead?

https://www.npmjs.com/package/glob

Also, I see some places that does not applies to our coding standard. Please fix them (I commented in the commit 341c3ac ).

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

I checked all the options for glob package, none of them offers recursive walk through of a directory.

`www/plugins` or `www/plugins/` will only match `www/plugins` and will not find the subdirectories unlike `.gitignore`. The only way to find that is to give pattern like `www/plugins/**`. 

`**` is the option given under the [glob primer](https://www.npmjs.com/package/glob#glob-primer) as well

I will still continue implementing the functionality using `glob` and will modify the options if found any.

**Comment by JW-Vinayak** [comment]
Another scenario for `monaca download` where directory exists on cloud but not locally. 
Let's say I add 'docs' directory on my Monaca cloud project and put an entry for it in my local `.monacaignore` file as follows.

`www/plugins`
`docs`

when I use `glob` to find `www/plugins` pattern locally, I will get list of say 5 files which I can check against files to be downloaded, and avoid downloading them.

But when I use 'glob' to find `docs` I will not find any files locally (because this folder does not exist locally) to check against files to be downloaded.

**Comment by masahirotanaka** [comment]
I wonder why you didn't specify `ignore` option, as it is mentioned in the document as follows:

> If you want the "everything except x" type of behavior, you can use *\* as the main pattern, and set an ignore for the things to exclude.

https://www.npmjs.com/package/glob

The basic idea is to grab all files, except some ignored files listed in .monacaignore and some hard-coded ignore files.

**Comment by JW-Vinayak** [comment]
Aah, now I got the idea. Earlier I misunderstood about using `ignore` option.

**Comment by JW-Vinayak** [comment]
So this solves `monaca upload` scenario. In `monaca download`, we do have all the files on cloud and we need to ignore some of them according to `.monacaignore`. How do we apply `glob` in this case?

**Comment by masahirotanaka** [comment]
In that case, please do not delete or overwrite files or directories that matches to .monacaignore. You can still create files or directories that are listed in .monacaignore but do not exist in the local filesystem.

**Comment by JW-Vinayak** [comment]
The code fails on windows due to [this](https://www.npmjs.com/package/glob#windows) issue. I am fixing it on windows machine.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka,

Please review this implementation.

**Comment by masahirotanaka** [comment]
Sorry for the late response.
Please fix the following implementation:
- On Windows machine, the line might be terminated with `\r\n` instead of `\n`. Please correct the way to split.
- Please trim each line, so that a line with only space will be ignored.
- `if (!/^\/(www\/|merges\/|plugins\/|[^/]*$)/.test(fn))` When upload, this should be also apply to .monacaignore. In other words, the user cannot add directories other than `www`, `merges` or `plugins`.
- `If yes then dont donwload it. If no, then download it.` => typo

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

Following actions are taken for the points you have mentioned above.
- The file contents are first split by \r\n and then by \n and then the result is concatenated.
- Line is trimmed
- The comment mentioned on this line was incorrect and it is corrected now. `(!/^\/(www\/|merges\/|plugins\/|[^/]*$)/.test(fn))` every file uploaded is first checked if it belongs to `www, merges` or `plugins` folder and then it is checked if it is ignored by user. Anything outside these 3 folders is directly ignored and not uploaded.
- Corrected typo.

**Comment by masahirotanaka** [comment]
Hi Vinayak,

I merged the source code.
I actually fixed the following items. Please aware from the next time.
- Unnecessary `console.log` in line 240
- Replaced tabs to 2 character white spaces.

**Comment by masahirotanaka** [comment]
I noticed that when uploading a project, it will not delete if that is a directory.
What is your intention for this?

in monaca.js, Line 1267:

`if (!localFiles.hasOwnProperty(f) && remoteFiles[f].type !== 'dir') {`

**Comment by masahirotanaka** [comment]
Anyways, I removed the condition and published as 1.1.6. Please let me know if there are any issues with it.

**Comment by JW-Vinayak** [comment]
Hi @masahirotanaka 

I will make it a point to delete stray debug prints. Regarding white spaces many times it happens that the existing code contains white spaces where there is no code change at all. Do I also delete those spaces? It unnecessarily shows a difference in pull request.

**Comment by pflugs30** [comment]
Does the `.monacaignore` feature work with the Monaca CLI tools?
