### ISSUE TITLE
Pass client_info to Login API

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-lib#3]
Please pass client_info parameter as follows:
- `version`: Passed from monaca-cli or Localkit. Should be something like: `monaca-cli 1.0.2`. Must be passed by the caller of the JavaScript API.
- `os`: Operating system that monaca-lib is running on.

**Comment by masahirotanaka** [comment]
Please also update monaca_cli after this change.

**Comment by argelius** [comment]
Thanks. I'll do this tomorrow
