### ISSUE TITLE
'File Save' action string value is not correct 

### ISSUE THREAD

**Issue by dotrikun** [monaca/monaca-lib#3]
'File Save' action string value is not correct.

The following is send value of 'File Save' in localkit.

json:  {
  "path":"/www/index.html",
  "contentHash":"79f3f65f",
  "action":**"saveFile"**,
  "projectId":"98f898cae48de540315abca5849d635c31459cc0c68ddddec9383237036fc053"
}

According to  [the document](https://docs.google.com/a/asial.co.jp/spreadsheets/d/1TJw6-oiqc7BlLOOZ4Ui03VcLpDKv0BQPxzOqpCfnUJk/edit?usp=sharing),
correct value is 

data: { 
  "action" : **"fileSave"**, 
  "projectId" : "<PROJECT_ID>", 
  "path" : "/www/index.html", 
  "body" : "BASE64 (optional)",
   contentHash: "crc32" 
}

**Comment by argelius** [comment]
四方さん、ありがとうございます！

直します！
