### ISSUE TITLE
Filter files when running getLocalProjectFiles()

### ISSUE THREAD

**Issue by masahirotanaka** [monaca/monaca-lib#31]
If the project has very large amount of files, it will cause trouble when getting file tree from the debugger. When calling this.monaca.getLocalProjectFiles() from Localkit.getProjectFiles(), it is actually filtering to get files in the "/www" directory, and ignoring all dot-files.

However, Monaca.getLocalProjectFiles() first get all files in the specified directory and calculating CRC32 hash for each found files, before filtering out the unnecessary files.

Therefore, please fix the logic and only calculate the hash files that are necessary to use.

**Comment by JW-Vinayak** [comment]
@masahirotanaka I will start working on it now.
