### ISSUE TITLE
Updated createApp tests

### ISSUE THREAD

**Issue by argelius** [monaca/monaca-lib#8]
@JW-Vinayak 

Could you please update the createApp test so it doesn't put the app in the monaca-lib directory? Please put it in a temporary directory somewhere.

**Comment by argelius** [comment]
Also, could you suppress the print as well in some way?

**Comment by JW-Vinayak** [comment]
@argelius I will work on this.

**Comment by argelius** [comment]
Thanks @JW-Vinayak ! :)

**Comment by JW-Vinayak** [comment]
@argelius I have updated createApp method and createApp test so that it doesn't put app in monaca-lib directory or any other temp directory for that matter. Also, the app folder created during test is deleted after test is over.
