### ISSUE TITLE
isTranspilable vue.js ?

### ISSUE THREAD

**Issue by quangv** [monaca/monaca-lib#87]
Hey there!

I'm new to Monaca, loving it so far. I am trying to use Monaca with vue-loader/webpack?

I started off with the "no framework, Blank Template", and thought I could use `monaca transpile` to build .vue files.

Seems like `monaca transpile` [only supports](https://github.com/monaca/monaca-lib/blob/master/src/monaca.js#L2417-L2426) react & angular2 ?

What's the best way to integrate [vue-loader](https://github.com/vuejs/vue-loader) with Monaca hybrid apps?

Thanks!

**Comment by frandiox** [comment]
@quangv I think all the information for that is stored in `myproject/.monaca/`. You can change that but maybe is easier to start with a React example and simply modify webpack configs and package.json. It could be possible that you need to install the build dependencies (like loaders, etc) in `~/.cordova/` (unless you change the path in the webpack configs).

**Comment by quangv** [comment]
@frankdiox cool thanks! I really like how monaca leverages webpack 👍

**Comment by frandiox** [comment]
@quangv Thanks. Would you mind to share the webpack config when you set it up for Vue? Probably at some point we will support Vue in the CLI and that would save us some time for transpiling Vue :sweat_smile:

**Comment by quangv** [comment]
@frankdiox this was my webpack config I got working.

https://gist.github.com/quangv/97088a598403cace05eee1e5b5dc7113

based off the react-min.

-Cheers

**Comment by quangv** [comment]
I just realized there was this...

https://github.com/argelius/vue-onsenui-navigator

hah 😅

**Comment by frandiox** [comment]
@quangv Thanks! Looks like we don't need to make many changes :)
I also forgot about that repo :sweat_smile: 
I will close this issue now.
